import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Step from '../components/Step'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>McFoxx Hilfen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>

      <main className={styles.main}>
        <Step></Step>
      </main>
      
      <Footer></Footer>
    </div>
  )
}
